### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by mlhoque** [chinthakagodawita/docker-hat#22]
I ran the following commands 

brew tap chinthakagodawita/homebrew-dh
brew update
brew install docker-hat
dh init --force

And than started PHP5.3.

**Comment by chinthakagodawita** [comment]
Can you get me a snippet of the apache logs? Can be found by going to <hostname>:8000 on the container or by running `docker logs <containername>`

**Comment by chinthakagodawita** [comment]
Is this still a problem?

**Comment by chinthakagodawita** [comment]
Will be fixed in [Helm](https://github.com/sitback/helm/), closing.
